export interface QuantumEvent {
  id: string;
  year: number;
  act: string;
  track: string;
  people: string[];
  title: string;
  discovery: string;
  evidence: string;
  significance: string;
  concept: string;
}

export const QUANTUM_EVENTS: QuantumEvent[] = [
  {
    id: 'evt-1610',
    year: 1610,
    act: 'I',
    track: 'foundations',
    people: ['Galileo Galilei'],
    title: "Telescopic Optics & Celestial Moons",
    discovery: 'Galileo refined the refracting telescope using convex and concave lenses, discovering the four major moons of Jupiter (Io, Europa, Ganymede, Callisto).',
    evidence: 'Sidereus Nuncius (1610). Observation of Jovian satellites proved celestial bodies do not all orbit the Earth, establishing observational optical physics.',
    significance: 'Revolutionized human understanding of optics and light transmission across cosmic distances, laying the groundwork for Rømer to measure the speed of light.',
    concept: 'refraction',
  },
  {
    id: 'evt-1621',
    year: 1621,
    act: 'I',
    track: 'foundations',
    people: ['Willebrord Snellius', 'René Descartes'],
    title: "Snell's Law of Refraction",
    discovery: 'Light passing between media with different refractive indices bends according to a precise trigonometric ratio: n₁ sin(θ₁) = n₂ sin(θ₂).',
    evidence: 'Snellius manuscript (1621); Descartes\' La Dioptrique (1637). Tested across water, glass, and quartz prisms.',
    significance: 'Established geometric optics and Snell-Descartes refraction law, showing that light trajectories follow Fermat\'s Principle of Least Action — a direct ancestor of Feynman\'s quantum path integral.',
    concept: 'refraction',
  },
  {
    id: 'evt-1665',
    year: 1665,
    act: 'I',
    track: 'foundations',
    people: ['Francesco Grimaldi', 'Isaac Newton'],
    title: "Grimaldi's Diffraction & Prism Dispersion",
    discovery: 'Grimaldi discovered that light bends into shadow zones behind opaque objects (diffraction). Concurrently, Newton split white light into a rainbow spectrum through glass prisms.',
    evidence: 'Physico-mathesis de lumine (1665). Newton\'s two-prism recombination experiment proved white light is a compound of all spectral colours.',
    significance: 'Revealed that light has internal spectral structure and exhibits wave-like diffraction bending around sharp obstacles, inaugurating physical optics.',
    concept: 'diffraction',
  },
  {
    id: 'evt-1676',
    year: 1676,
    act: 'I',
    track: 'foundations',
    people: ['Ole Rømer'],
    title: "Finite Speed of Light (c)",
    discovery: 'By observing irregularities in the eclipses of Jupiter\'s moon Io as Earth moved closer and farther from Jupiter, Rømer proved light travels at a finite velocity.',
    evidence: 'Paris Observatory measurements presented to the Académie des Sciences (1676). Light required ~22 minutes to traverse the diameter of Earth\'s orbit.',
    significance: 'Shattered the ancient dogma of instantaneous light propagation, proving c is a universal physical constant that underpins all relativistic and quantum field equations (E=mc², E=hν).',
    concept: 'speed-of-light',
  },
  {
    id: 'evt-1678',
    year: 1678,
    act: 'I',
    track: 'foundations',
    people: ['Christiaan Huygens'],
    title: "Huygens' Wave Principle",
    discovery: 'Light propagates as a wave, each point on a wavefront acting as a source of secondary wavelets. Huygens explained reflection, refraction, and double refraction geometrically.',
    evidence: 'Traité de la Lumière (1690). Huygens correctly predicted the double refraction of Iceland spar (calcite) using wavelet construction.',
    significance: 'Introduced the wave picture of light that would eventually collide with Newton\'s corpuscular model, making the wave–particle duality crisis inevitable two centuries later.',
    concept: 'wave',
  },
  {
    id: 'evt-1704',
    year: 1704,
    act: 'I',
    track: 'foundations',
    people: ['Isaac Newton'],
    title: 'Opticks & Corpuscular Theory',
    discovery: 'Newton published Opticks, arguing light consists of discrete, tiny particles ("corpuscles"). He formulated the mathematical laws of reflection and prismatic dispersion.',
    evidence: 'Opticks (1704). Prismatic spectrum experiments, Newton\'s rings, and light ray trajectory geometry.',
    significance: 'Established the particle foundation of light. While classical wave optics later surpassed Newton\'s specific model, Einstein resurrected light particles as photons (E=hν) in 1905, validating Newton\'s particle intuition.',
    concept: 'opticks',
  },
  {
    id: 'evt-1727',
    year: 1727,
    act: 'I',
    track: 'foundations',
    people: ['James Bradley'],
    title: 'Stellar Aberration & Light Velocity',
    discovery: 'Bradley observed an apparent cyclical shift in the positions of stars throughout the year, caused by the vector addition of Earth\'s orbital velocity and the finite velocity of incoming starlight.',
    evidence: 'Observations of Gamma Draconis with a zenith telescope at Kew (1728). Calculated the speed of light as c ≈ 301,000 km/s, within 1% of the modern value.',
    significance: 'Provided the first direct physical measurement of the speed of light from Earth and proved the motion of the Earth around the Sun, essential for photon momentum calculations (p=h/λ).',
    concept: 'aberration',
  },
  {
    id: 'evt-1785',
    year: 1785,
    act: 'I',
    track: 'foundations',
    people: ['Charles-Augustin de Coulomb'],
    title: "Coulomb's Law & Electrostatic Inverse Square",
    discovery: 'The electrostatic force between two charged spheres is directly proportional to the product of their charges and inversely proportional to the square of the distance between them: F = k·(q₁q₂)/r².',
    evidence: 'Torsion balance experiments at the Paris Academy of Sciences. Coulomb measured minuscule forces with hair-thin metallic wires.',
    significance: 'The foundational mathematical equation of atomic and quantum chemistry. The Coulomb potential V(r) = -e²/(4πε₀r) is the exact force binding electrons to the atomic nucleus in the Schrödinger equation.',
    concept: 'coulomb',
  },
  {
    id: 'evt-1793',
    year: 1793,
    act: 'I',
    track: 'foundations',
    people: ['Thomas Young'],
    title: 'Acoustic-Optical Wave Analogy',
    discovery: 'Young demonstrated that sound waves and water waves produce interference fringes when passing through apertures, and formulated the hypothesis that light undergoes the identical wave interference.',
    evidence: 'Observations on Vision and sound propagation experiments presented to the Royal Society.',
    significance: 'The conceptual precursor to the 1801 Double-Slit experiment. Directly challenged Newton\'s corpuscular orthodoxy by demonstrating that light obeys linear wave superposition.',
    concept: 'wave',
  },
  {
    id: 'evt-1801',
    year: 1801,
    act: 'II',
    track: 'foundations',
    people: ['Thomas Young'],
    title: 'Double-Slit Experiment',
    discovery: 'Light passing through two narrow slits produces an interference pattern of bright and dark fringes on a screen — impossible if light were purely particle-like.',
    evidence: 'Young\'s Bakerian Lecture to the Royal Society. The fringe spacing matched his wave calculations precisely. Later repeated with electrons, atoms, and molecules — always the same result.',
    significance: 'The most profound experiment in physics. Confirmed light is a wave. When later repeated with single particles, it revealed that quantum objects interfere with themselves — the heart of quantum weirdness.',
    concept: 'double-slit',
  },
  {
    id: 'evt-1814',
    year: 1814,
    act: 'II',
    track: 'foundations',
    people: ['Joseph von Fraunhofer'],
    title: 'Spectral Lines',
    discovery: 'Dark lines appear at precise wavelengths in the solar spectrum. Each chemical element produces a unique pattern of spectral lines — an atomic fingerprint.',
    evidence: 'Fraunhofer mapped 574 dark lines in the solar spectrum with a diffraction grating. Later, Kirchhoff and Bunsen identified elements by their emission spectra.',
    significance: 'Spectral lines demanded an explanation. Why do atoms emit only specific frequencies? This question drove the development of atomic models culminating in quantum mechanics.',
    concept: 'spectrum',
  },
  {
    id: 'evt-1865',
    year: 1865,
    act: 'II',
    track: 'foundations',
    people: ['James Clerk Maxwell'],
    title: "Maxwell's Electromagnetic Theory",
    discovery: 'Electric and magnetic fields propagate together as waves at the speed of light. Light is an electromagnetic wave. Maxwell unified electricity, magnetism, and optics in four equations.',
    evidence: 'A Dynamical Theory of the Electromagnetic Field (1865). Maxwell predicted electromagnetic waves and calculated their speed as c ≈ 3×10⁸ m/s — matching the known speed of light exactly.',
    significance: 'The pinnacle of classical physics. Yet Maxwell\'s equations implied a catastrophic failure — the ultraviolet catastrophe — that would force Planck to introduce the quantum.',
    concept: 'wave',
  },
  {
    id: 'evt-1887',
    year: 1887,
    act: 'II',
    track: 'foundations',
    people: ['Heinrich Hertz'],
    title: 'Photoelectric Effect Observed',
    discovery: 'Ultraviolet light striking a metal surface ejects electrons. Crucially, the electron energy depends on light frequency, not intensity — inexplicable by classical wave theory.',
    evidence: 'Hertz observed sparks were enhanced by UV light. Lenard (1902) showed ejected electron energy scales with frequency, not brightness.',
    significance: 'The anomaly Einstein explained in 1905 by proposing light comes in discrete packets — photons. This single experiment demanded the quantum.',
    concept: 'photoelectric',
  },
  {
    id: 'evt-1900',
    year: 1900,
    act: 'III',
    track: 'foundations',
    people: ['Max Planck'],
    title: "Planck's Quantum Hypothesis",
    discovery: 'To match the observed blackbody radiation spectrum, energy must be emitted in discrete packets: E = hν, where h is Planck\'s constant. Planck called this a "mathematical trick."',
    evidence: 'Planck presented his formula to the German Physical Society on 14 December 1900 — now celebrated as the birthday of quantum theory. His formula matched experiment perfectly across all frequencies.',
    significance: 'The birth of the quantum. Planck\'s reluctant introduction of energy quantisation ended the ultraviolet catastrophe and opened a new era of physics.',
    concept: 'blackbody',
  },
  {
    id: 'evt-1905',
    year: 1905,
    act: 'III',
    track: 'foundations',
    people: ['Albert Einstein'],
    title: 'Photon Theory of Light',
    discovery: 'Einstein proposed that light itself is quantised into photons (light quanta) of energy E = hν. This explained the photoelectric effect: each photon ejects one electron if its energy exceeds the work function.',
    evidence: 'Einstein\'s paper "On a Heuristic Point of View Concerning the Production and Transformation of Light" (1905). Millikan\'s 1916 experiments confirmed Einstein\'s predictions to high precision.',
    significance: 'Einstein won the 1921 Nobel Prize for this work. The photon concept forced physicists to accept that light is simultaneously wave and particle — the first clear statement of wave–particle duality.',
    concept: 'photoelectric',
  },
  {
    id: 'evt-1909',
    year: 1909,
    act: 'III',
    track: 'foundations',
    people: ['Geoffrey Taylor'],
    title: 'Single-Photon Interference',
    discovery: 'Even when light is so dim that only one photon is present at a time, an interference pattern gradually builds up on a photographic plate over weeks of exposure.',
    evidence: 'Taylor\'s experiment at Cambridge used extremely attenuated light from a gas flame behind a needle. The fringes were identical to those with bright light.',
    significance: 'A single photon interferes with itself. This is the experimental signature of quantum superposition — the photon passes through both slits simultaneously.',
    concept: 'double-slit',
  },
  {
    id: 'evt-1911',
    year: 1911,
    act: 'III',
    track: 'foundations',
    people: ['Ernest Rutherford'],
    title: 'Nuclear Atom Model',
    discovery: 'Alpha particles aimed at gold foil occasionally bounce straight back — impossible if mass were diffuse. Rutherford deduced a tiny, dense, positive nucleus surrounded by orbiting electrons.',
    evidence: 'The Geiger-Marsden experiment at Manchester. About 1 in 8000 alpha particles deflected more than 90°. Rutherford: "It was as if you fired artillery shells at tissue paper and they came back and hit you."',
    significance: 'The nuclear model immediately raised a crisis: orbiting electrons should radiate energy and spiral into the nucleus in nanoseconds. This crisis demanded Bohr\'s quantum fix.',
    concept: 'bohr',
  },
  {
    id: 'evt-1913',
    year: 1913,
    act: 'III',
    track: 'foundations',
    people: ['Niels Bohr'],
    title: "Bohr's Atomic Model",
    discovery: 'Electrons orbit the nucleus only in specific allowed shells with quantised angular momentum. Electrons jumping between shells emit or absorb photons of precise frequency — explaining spectral lines.',
    evidence: 'Bohr\'s model predicted the hydrogen spectrum (Balmer series) with extraordinary accuracy. The Rydberg formula emerged naturally from his quantisation condition.',
    significance: 'The first successful quantum model of the atom. Though later superseded by wave mechanics, Bohr\'s picture introduced the concept of quantised energy levels that remains central to all of modern chemistry.',
    concept: 'bohr',
  },
  {
    id: 'evt-1922',
    year: 1922,
    act: 'III',
    track: 'foundations',
    people: ['Otto Stern', 'Walther Gerlach'],
    title: 'Stern-Gerlach Experiment',
    discovery: 'A beam of silver atoms passing through an inhomogeneous magnetic field splits into exactly two discrete spots — not a continuous smear. Electron spin is quantised.',
    evidence: 'The Stern-Gerlach experiment at Frankfurt. The two discrete bands directly demonstrated space quantisation and, eventually, the existence of electron spin.',
    significance: 'Direct proof that quantum angular momentum is quantised in discrete values — not a classical continuum. Spin ½ particles became central to quantum field theory and the Pauli exclusion principle.',
    concept: 'uncertainty',
  },
  {
    id: 'evt-1923',
    year: 1923,
    act: 'III',
    track: 'foundations',
    people: ['Louis de Broglie'],
    title: 'Matter Waves',
    discovery: 'Every particle with momentum p has an associated wavelength λ = h/p. Matter, like light, has wave character. This is wave–particle duality extended to all matter.',
    evidence: 'De Broglie\'s 1924 doctoral thesis. Confirmed experimentally by Davisson and Germer (1927) who observed electron diffraction from nickel crystal — identical to X-ray diffraction.',
    significance: 'The conceptual leap that led Schrödinger to write his wave equation. Every object in the universe — electrons, atoms, molecules, even buckyballs — has a de Broglie wavelength.',
    concept: 'wave',
  },
  {
    id: 'evt-1925',
    year: 1925,
    act: 'III',
    track: 'foundations',
    people: ['Werner Heisenberg'],
    title: 'Matrix Mechanics',
    discovery: 'Heisenberg reformulated quantum theory using matrices of observable quantities, abandoning the notion of electron orbits entirely. Only measurable quantities appear in the theory.',
    evidence: 'Heisenberg\'s Helgoland paper (July 1925). Born and Jordan quickly formalised it as matrix mechanics. The formalism correctly predicted atomic spectra.',
    significance: 'The first complete formulation of quantum mechanics. Heisenberg\'s insistence on observable quantities only anticipated the Copenhagen interpretation and the measurement problem.',
    concept: 'uncertainty',
  },
  {
    id: 'evt-1926-schrodinger',
    year: 1926,
    act: 'III',
    track: 'foundations',
    people: ['Erwin Schrödinger'],
    title: "Schrödinger's Wave Equation",
    discovery: 'The time-dependent Schrödinger equation iℏ∂ψ/∂t = Ĥψ governs how quantum states evolve. The wavefunction ψ encodes all information about a quantum system.',
    evidence: 'Schrödinger\'s four 1926 papers in Annalen der Physik. He showed his wave mechanics and Heisenberg\'s matrix mechanics are mathematically equivalent.',
    significance: 'The master equation of quantum mechanics. Every quantum calculation — from hydrogen orbitals to quantum computers — ultimately traces back to this equation.',
    concept: 'wave',
  },
  {
    id: 'evt-1926-born',
    year: 1926,
    act: 'III',
    track: 'foundations',
    people: ['Max Born'],
    title: 'Probability Interpretation',
    discovery: '|ψ|² gives the probability density of finding a particle at a given location. The wavefunction is not a physical wave but a probability amplitude.',
    evidence: 'Born\'s 1926 paper on collision processes. He noted: "The motion of particles follows probability laws, but the probability itself propagates according to causal laws."',
    significance: 'The probabilistic interpretation is the most philosophically radical aspect of quantum mechanics. It ended determinism in fundamental physics and sparked the Einstein–Bohr debates.',
    concept: 'wave',
  },
  {
    id: 'evt-1927-uncertainty',
    year: 1927,
    act: 'III',
    track: 'foundations',
    people: ['Werner Heisenberg'],
    title: 'Uncertainty Principle',
    discovery: 'ΔxΔp ≥ ℏ/2: position and momentum cannot both be known precisely. This is not a limitation of measurement technology — it is a fundamental feature of nature.',
    evidence: 'Heisenberg\'s 1927 paper, illustrated with the gamma-ray microscope thought experiment. Robertson later derived the general form for any pair of non-commuting observables.',
    significance: 'The most famous result in quantum mechanics. It sets absolute limits on knowledge, rules out hidden-variable theories (with Bell\'s later work), and stabilises atoms — electrons cannot collapse to the nucleus.',
    concept: 'uncertainty',
  },
  {
    id: 'evt-1927-copenhagen',
    year: 1927,
    act: 'III',
    track: 'foundations',
    people: ['Niels Bohr', 'Werner Heisenberg'],
    title: 'Copenhagen Interpretation',
    discovery: 'Quantum systems do not have definite properties until measured. The act of measurement collapses the wavefunction. Wave and particle descriptions are complementary, not contradictory.',
    evidence: 'Solvay Conference, Brussels, 1927. Bohr and Heisenberg debated Einstein, who sought to refute the interpretation with thought experiments. Bohr countered each one.',
    significance: 'The dominant interpretation of quantum mechanics for a century. It pragmatically sidesteps ontological questions ("shut up and calculate") while remaining predictively perfect.',
    concept: 'wave',
  },
  {
    id: 'evt-1928',
    year: 1928,
    act: 'III',
    track: 'foundations',
    people: ['Paul Dirac'],
    title: 'Dirac Equation & Antimatter',
    discovery: 'The relativistic quantum equation for the electron (iγᵘ∂ᵤ − m)ψ = 0 automatically predicts electron spin and, startlingly, negative-energy solutions — interpreted as antiparticles.',
    evidence: 'Dirac\'s 1928 paper. Carl Anderson discovered the positron (anti-electron) in 1932, confirming the prediction. Dirac called it "the most unexpected discovery in physics."',
    significance: 'Unified quantum mechanics and special relativity. Predicted antimatter before it was observed. The foundation of quantum field theory and the Standard Model of particle physics.',
    concept: 'particle',
  },
  {
    id: 'evt-1932',
    year: 1932,
    act: 'III',
    track: 'foundations',
    people: ['John von Neumann'],
    title: 'Mathematical Foundations',
    discovery: 'Von Neumann placed quantum mechanics on rigorous mathematical footing using Hilbert spaces, self-adjoint operators, and the spectral theorem. He formalised the measurement postulate.',
    evidence: 'Mathematische Grundlagen der Quantenmechanik (1932). Von Neumann\'s formalism is the language all modern quantum computation uses.',
    significance: 'Made quantum mechanics mathematically airtight. Introduced the density matrix, quantum entropy, and the first proof (flawed but influential) against hidden variables.',
    concept: 'uncertainty',
  },
  {
    id: 'evt-1935-epr',
    year: 1935,
    act: 'III',
    track: 'foundations',
    people: ['Albert Einstein', 'Boris Podolsky', 'Nathan Rosen'],
    title: 'EPR Paradox',
    discovery: 'If quantum mechanics is complete, then measuring one particle of an entangled pair instantly determines the other\'s properties — "spooky action at a distance." Einstein argued this proved QM incomplete.',
    evidence: 'Einstein, Podolsky, Rosen paper (1935). Schrödinger responded with his cat thought experiment and coined the term "entanglement."',
    significance: 'Framed the deepest question in quantum foundations. Bell\'s 1964 theorem and Aspect\'s 1982 experiments showed Einstein was wrong — entanglement is real, not a sign of incompleteness.',
    concept: 'entanglement',
  },
  {
    id: 'evt-1935-cat',
    year: 1935,
    act: 'III',
    track: 'foundations',
    people: ['Erwin Schrödinger'],
    title: "Schrödinger's Cat",
    discovery: 'A cat in a box linked to a quantum decay event is — according to the wavefunction — simultaneously alive and dead until observed. Schrödinger intended this as a reductio ad absurdum of the Copenhagen interpretation.',
    evidence: 'Schrödinger\'s 1935 paper "Die gegenwärtige Situation in der Quantenmechanik." The thought experiment remains unresolved and drives decoherence research.',
    significance: 'The most famous thought experiment in science. It sharpened the measurement problem and the question of where the quantum-classical boundary lies.',
    concept: 'wave',
  },
  {
    id: 'evt-1947',
    year: 1947,
    act: 'III',
    track: 'computing',
    people: ['William Shockley', 'John Bardeen', 'Walter Brattain'],
    title: 'Transistor Invented',
    discovery: 'The point-contact transistor amplifies electrical signals using quantum tunnelling and band-gap engineering in semiconductors — a direct application of quantum mechanics.',
    evidence: 'Bell Labs, 23 December 1947. The transistor replaced vacuum tubes and enabled modern computing. Shockley, Bardeen, and Brattain shared the 1956 Nobel Prize.',
    significance: 'Every modern computer, smartphone, and quantum chip is built from transistors. Quantum mechanics is not just a theory — it is the engineering principle of the information age.',
    concept: 'transistor',
  },
  {
    id: 'evt-1957',
    year: 1957,
    act: 'III',
    track: 'foundations',
    people: ['Hugh Everett III'],
    title: 'Many-Worlds Interpretation',
    discovery: 'The wavefunction never collapses. Every quantum measurement causes the universe to branch into parallel worlds, one for each outcome. All branches are equally real.',
    evidence: 'Everett\'s Princeton PhD thesis (1957), largely ignored until DeWitt popularised it in the 1970s. Now one of the most seriously discussed interpretations among physicists.',
    significance: 'Eliminates the measurement problem by abolishing collapse. At the cost of infinitely many parallel universes. Raises profound questions about probability and identity.',
    concept: 'wave',
  },
  {
    id: 'evt-1960',
    year: 1960,
    act: 'III',
    track: 'computing',
    people: ['Theodore Maiman'],
    title: 'First Laser',
    discovery: 'Stimulated emission of coherent light — predicted by Einstein in 1917 using quantum transition probabilities — is achieved in a ruby crystal pumped by a flashlamp.',
    evidence: 'Maiman\'s paper in Nature (1960). The laser produces highly coherent, monochromatic light through population inversion and stimulated emission.',
    significance: 'Lasers are the workhorses of quantum technology: they cool atoms to nanokelvin, read qubits, transmit quantum keys, and probe matter with femtosecond precision.',
    concept: 'photoelectric',
  },
  {
    id: 'evt-1964',
    year: 1964,
    act: 'III',
    track: 'foundations',
    people: ['John Bell'],
    title: "Bell's Theorem",
    discovery: 'Any local hidden-variable theory must satisfy Bell inequalities. Quantum mechanics predicts violations. If experiment violates Bell inequalities, nature is fundamentally non-local.',
    evidence: 'Bell\'s 1964 paper in Physics. Clauser (1972) and Aspect (1982) experimentally violated Bell inequalities. Loophole-free tests by Hensen et al. (2015) confirmed the result definitively.',
    significance: 'The most important theorem in the foundations of physics. It transformed EPR from philosophy to experiment and proved that quantum entanglement is a real, irreducible feature of nature.',
    concept: 'entanglement',
  },
  {
    id: 'evt-1973',
    year: 1973,
    act: 'III',
    track: 'foundations',
    people: ['Charles Bennett', 'Gilles Brassard'],
    title: 'Reversible Computation',
    discovery: 'Bennett showed that computation can be performed reversibly without erasing information — critical for quantum computation where unitary evolution is reversible.',
    evidence: 'Bennett\'s 1973 IBM Journal paper. Reversibility is a prerequisite for quantum gates, which must be unitary (hence invertible).',
    significance: 'Laid the thermodynamic and logical foundation for quantum computing. Showed that Landauer\'s erasure principle need not limit computation.',
    concept: 'transistor',
  },
  {
    id: 'evt-1981',
    year: 1981,
    act: 'III',
    track: 'computing',
    people: ['Richard Feynman'],
    title: 'Quantum Simulation Proposed',
    discovery: 'Classical computers cannot efficiently simulate quantum systems. Feynman proposed using a quantum computer — a programmable quantum system — to simulate other quantum systems.',
    evidence: 'Feynman\'s 1981 talk "Simulating Physics with Computers." He argued that exponential classical overhead could be avoided with a quantum machine.',
    significance: 'The founding vision of quantum computing. Feynman\'s insight drives today\'s quantum chemistry and materials simulation — the most near-term commercially valuable quantum application.',
    concept: 'bloch',
  },
  {
    id: 'evt-1982',
    year: 1982,
    act: 'III',
    track: 'foundations',
    people: ['Alain Aspect'],
    title: 'Bell Inequality Violation Confirmed',
    discovery: 'Aspect\'s experiments with entangled photon pairs at Orsay definitively violated Bell inequalities, ruling out local hidden variables with high statistical confidence.',
    evidence: 'Aspect, Grangier, Roger (1982). The experiment used time-varying analyser orientations to close the locality loophole. Three Nobel Prizes were awarded for this line of work in 2022.',
    significance: 'Experimental proof that nature is non-local at the quantum level. Entanglement is not a bookkeeping trick — it is a real physical resource used in quantum cryptography and teleportation.',
    concept: 'entanglement',
  },
  {
    id: 'evt-1984',
    year: 1984,
    act: 'III',
    track: 'computing',
    people: ['Charles Bennett', 'Gilles Brassard'],
    title: 'BB84 Quantum Cryptography',
    discovery: 'The BB84 protocol uses quantum states to distribute cryptographic keys with information-theoretic security — any eavesdropper disturbs the quantum states and is detected.',
    evidence: 'Bennett and Brassard\'s 1984 paper. First experimental demonstration by Bennett et al. (1992) over 30 cm. Commercial QKD systems now operate over hundreds of kilometres of fibre.',
    significance: 'The first quantum information protocol. Proved that quantum mechanics offers security guarantees impossible with classical physics — the foundation of quantum cryptography.',
    concept: 'entanglement',
  },
  {
    id: 'evt-1985',
    year: 1985,
    act: 'III',
    track: 'computing',
    people: ['David Deutsch'],
    title: 'Universal Quantum Computer',
    discovery: 'Deutsch defined the universal quantum Turing machine and showed that a quantum computer can simulate any physical system efficiently, including itself.',
    evidence: 'Deutsch\'s 1985 paper in Proceedings of the Royal Society. He also introduced the first quantum algorithm (Deutsch\'s problem) showing quantum speedup over classical.',
    significance: 'The theoretical birth of quantum computing as a discipline. Deutsch\'s model is the foundation on which Shor, Grover, and every subsequent quantum algorithm is built.',
    concept: 'bloch',
  },
  {
    id: 'evt-1993',
    year: 1993,
    act: 'III',
    track: 'computing',
    people: ['Charles Bennett', 'Gilles Brassard', 'Claude Crépeau', 'Richard Jozsa', 'Asher Peres', 'William Wootters'],
    title: 'Quantum Teleportation Protocol',
    discovery: 'An unknown quantum state can be transmitted perfectly using a shared entangled pair and two classical bits. The state is destroyed at the sender and recreated at the receiver.',
    evidence: 'Bennett et al. 1993 paper. Experimentally demonstrated by Bouwmeester et al. (1997) with photons; later with atoms, ions, and across satellite links.',
    significance: 'Proved that quantum information can be moved without a physical carrier. Teleportation is the primitive operation of quantum networks and distributed quantum computing.',
    concept: 'entanglement',
  },
  {
    id: 'evt-1994',
    year: 1994,
    act: 'III',
    track: 'computing',
    people: ['Peter Shor'],
    title: "Shor's Factoring Algorithm",
    discovery: 'A quantum computer can factor large integers in polynomial time using quantum Fourier transform and period-finding. This breaks RSA encryption.',
    evidence: 'Shor\'s 1994 paper at STOC. The algorithm requires a fault-tolerant quantum computer with thousands of logical qubits — not yet built, but the threat drives post-quantum cryptography.',
    significance: 'The single result that convinced the world quantum computing matters. Governments and companies have invested billions to either build Shor-capable machines or develop post-quantum cryptography.',
    concept: 'shor',
  },
  {
    id: 'evt-1996',
    year: 1996,
    act: 'III',
    track: 'computing',
    people: ['Lov Grover'],
    title: "Grover's Search Algorithm",
    discovery: 'A quantum computer can search an unsorted database of N items in O(√N) steps — a quadratic speedup over classical O(N) search.',
    evidence: 'Grover\'s 1996 paper. Proven to be optimal: no quantum algorithm can do better for unstructured search. Demonstrated on small quantum processors.',
    significance: 'Shows quantum speedup for a problem with no obvious quantum structure. The algorithm is a subroutine in many larger quantum algorithms and has applications in optimisation and cryptanalysis.',
    concept: 'bloch',
  },
  {
    id: 'evt-1997',
    year: 1997,
    act: 'III',
    track: 'computing',
    people: ['Peter Shor', 'Andrew Steane'],
    title: 'Quantum Error Correction',
    discovery: 'Quantum information can be protected against decoherence by encoding one logical qubit in multiple physical qubits. The Shor 9-qubit and Steane 7-qubit codes were the first.',
    evidence: 'Shor (1995) and Steane (1996) codes. The threshold theorem (1996) proved that arbitrarily long quantum computation is possible if the error rate per gate is below a threshold (~1%).',
    significance: 'Without error correction, quantum computers are too noisy to be useful. QEC is the engineering challenge of the century — current quantum processors have ~0.1–1% error rates, near the threshold.',
    concept: 'error-correction',
  },
  {
    id: 'evt-1998',
    year: 1998,
    act: 'III',
    track: 'computing',
    people: ['Isaac Chuang', 'Neil Gershenfeld'],
    title: 'First Quantum Algorithm Demonstrated',
    discovery: 'Deutsch\'s algorithm was run on a 2-qubit NMR quantum processor — the first experimental demonstration of a quantum algorithm outperforming its classical counterpart.',
    evidence: 'Chuang and Gershenfeld (1998) in Science. The NMR approach used nuclear spins in molecules as qubits, manipulated by radio-frequency pulses.',
    significance: 'Proof of concept for quantum computing hardware. Though NMR is not scalable, this experiment established the experimental paradigm and drove the search for better qubit platforms.',
    concept: 'bloch',
  },
  {
    id: 'evt-2001',
    year: 2001,
    act: 'IV',
    track: 'computing',
    people: ['IBM Research'],
    title: "Shor's Algorithm on 7 Qubits",
    discovery: 'IBM\'s NMR quantum computer factored 15 = 3 × 5 using Shor\'s algorithm on 7 qubits — the first experimental demonstration of Shor\'s algorithm.',
    evidence: 'Vandersypen et al. (2001) in Nature. The 7-qubit system used perfluorobutadienyl iron complex as the quantum register.',
    significance: 'Demonstrated that Shor\'s algorithm works in principle. The scale required to threaten real RSA keys (2048-bit) remains orders of magnitude beyond current hardware.',
    concept: 'shor',
  },
  {
    id: 'evt-2007',
    year: 2007,
    act: 'IV',
    track: 'computing',
    people: ['D-Wave Systems'],
    title: 'First Commercial Quantum Annealer',
    discovery: 'D-Wave released the first commercial quantum computing system using quantum annealing — a heuristic optimisation technique exploiting quantum tunnelling.',
    evidence: 'D-Wave One (2007), later purchased by Google and NASA. Debate continues about whether D-Wave systems demonstrate genuine quantum speedup.',
    significance: 'Quantum computing entered commerce. D-Wave systems are used for optimisation problems in logistics, finance, and materials science, regardless of the theoretical debate.',
    concept: 'bloch',
  },
  {
    id: 'evt-2012',
    year: 2012,
    act: 'IV',
    track: 'foundations',
    people: ['Serge Haroche', 'David Wineland'],
    title: 'Nobel Prize: Controlling Quantum Systems',
    discovery: 'Haroche (cavity QED with photons) and Wineland (trapped ion qubits) developed methods to measure and manipulate individual quantum systems without destroying them.',
    evidence: 'Nobel Prize in Physics 2012. Wineland\'s trapped ions are now the leading platform for high-fidelity quantum computing; Haroche\'s photon-counting techniques underpin quantum networking.',
    significance: 'Experimental mastery of individual quantum objects. Their techniques are the foundation of modern quantum hardware: trapped ions, circuit QED, and quantum sensors.',
    concept: 'bloch',
  },
  {
    id: 'evt-2016',
    year: 2016,
    act: 'IV',
    track: 'computing',
    people: ['IBM Research'],
    title: 'IBM Quantum Experience',
    discovery: 'IBM made a 5-qubit quantum processor accessible via the cloud — the first publicly available quantum computer. Within a year, 40,000 users ran 275,000 experiments.',
    evidence: 'IBM Quantum Experience launched May 2016. Now IBM Quantum offers processors up to 433 qubits (Eagle, Osprey, Condor series) to researchers worldwide.',
    significance: 'Democratised quantum computing. Research moved from theory to experiment for thousands of groups globally. Accelerated algorithm development, error characterisation, and quantum education.',
    concept: 'bloch',
  },
  {
    id: 'evt-2017',
    year: 2017,
    act: 'IV',
    track: 'computing',
    people: ['Mikhail Lukin', 'Harvard Quantum Initiative'],
    title: '51-Qubit Quantum Simulator',
    discovery: 'A programmable quantum simulator of 51 qubits using neutral atoms in optical tweezers simulated quantum phase transitions beyond classical supercomputer capability.',
    evidence: 'Bernien et al. (2017) in Nature. The system explored Rydberg atom arrays — now a leading platform for quantum simulation and computation.',
    significance: 'First clear demonstration of quantum simulation beyond classical reach. Rydberg atom arrays are now competing with superconducting and trapped-ion platforms for quantum advantage.',
    concept: 'bloch',
  },
  {
    id: 'evt-2019',
    year: 2019,
    act: 'IV',
    track: 'computing',
    people: ['Google AI Quantum'],
    title: 'Quantum Supremacy Claimed',
    discovery: 'Google\'s 53-qubit Sycamore processor performed a sampling task in 200 seconds that Google estimated would take a classical supercomputer 10,000 years.',
    evidence: 'Arute et al. (2019) in Nature. IBM contested the 10,000-year estimate (arguing ~2.5 days with optimised classical algorithms), but the quantum speedup for this specific task is not disputed.',
    significance: 'The first credible claim of quantum computational advantage. Marked a milestone analogous to the Wright Brothers\' first flight — not yet useful, but proof of the principle.',
    concept: 'bloch',
  },
  {
    id: 'evt-2022',
    year: 2022,
    act: 'IV',
    track: 'foundations',
    people: ['Alain Aspect', 'John Clauser', 'Anton Zeilinger'],
    title: "Nobel Prize: Bell Tests & Entanglement",
    discovery: 'The Nobel Committee recognised the experimental work establishing Bell inequality violations and pioneering quantum information science — entanglement is real and useful.',
    evidence: 'Nobel Prize in Physics 2022. Zeilinger\'s group demonstrated entanglement-based quantum teleportation, quantum cryptography, and multi-photon entanglement.',
    significance: 'The highest scientific recognition for quantum foundations becoming quantum technology. Entanglement moved from Einstein\'s philosophical objection to a commercial resource.',
    concept: 'entanglement',
  },
  {
    id: 'evt-2023',
    year: 2023,
    act: 'IV',
    track: 'computing',
    people: ['IBM Research'],
    title: '1000+ Qubit Processor',
    discovery: 'IBM unveiled the 1121-qubit Condor processor and the 133-qubit Heron processor with improved connectivity and reduced error rates, alongside a quantum-centric supercomputing roadmap.',
    evidence: 'IBM Quantum Summit, November 2023. Heron achieves 5× improvement in device performance over Eagle. The roadmap targets fault-tolerant quantum computing by 2033.',
    significance: 'Quantum hardware is scaling. The engineering challenge has shifted from qubit count to qubit quality. Fault-tolerant quantum advantage for commercially relevant problems is now a credible 10-year target.',
    concept: 'error-correction',
  },
  {
    id: 'evt-2024',
    year: 2024,
    act: 'IV',
    track: 'computing',
    people: ['Google DeepMind', 'Google Quantum AI'],
    title: 'Willow: Below-Threshold Error Correction',
    discovery: 'Google\'s Willow chip demonstrated that adding more physical qubits exponentially reduces logical error rates — the first experimental confirmation of below-threshold quantum error correction.',
    evidence: 'Acharya et al. (2024) in Nature. Willow also performed a benchmark computation in under 5 minutes that would take a classical supercomputer 10²⁵ years.',
    significance: 'The most important experimental result in quantum computing since Google\'s 2019 supremacy claim. Below-threshold error correction is the key milestone on the path to fault-tolerant quantum computers.',
    concept: 'error-correction',
  },
];

export interface Century {
  id: string;
  label: string;
  range: string;
  yearRange: [number, number];
  events: QuantumEvent[];
  count: number;
  tracks: string[];
}

export const CENTURIES: Century[] = (() => {
  const defs = [
    { id: 'c17', label: '17th Century', range: '1600–1699', yearRange: [1600, 1699] as [number,number] },
    { id: 'c18', label: '18th Century', range: '1700–1799', yearRange: [1700, 1799] as [number,number] },
    { id: 'c19', label: '19th Century', range: '1800–1899', yearRange: [1800, 1899] as [number,number] },
    { id: 'c20', label: '20th Century', range: '1900–1999', yearRange: [1900, 1999] as [number,number] },
    { id: 'c21', label: '21st Century', range: '2000–present', yearRange: [2000, 2100] as [number,number] },
  ];
  return defs.map(d => {
    const events = QUANTUM_EVENTS.filter(e => e.year >= d.yearRange[0] && e.year <= d.yearRange[1]);
    const tracks = [...new Set(events.map(e => e.track))];
    return { ...d, events, count: events.length, tracks };
  }).filter(c => c.count > 0);
})();